### ISSUE TITLE
Executable does not execute on Windows

### ISSUE THREAD

**Issue by tszynalski** [scottaxcell/winddcutil#11]
"The specified executable is not a valid application for this OS platform"

**Comment by scottaxcell** [comment]
You have to provide more details to get assistance with this…

What Windows version are you using? What’s the output in the command prompt? Which version of winddcutil are you using?

**Comment by tszynalski** [comment]
I'm sorry -- the file must not have downloaded correctly earlier. I should have checked the filesize. It executes fine.
