### ISSUE TITLE
Virus Total report...

### ISSUE THREAD

**Issue by 70V07** [scottaxcell/winddcutil#12]
_pls someone reply to my issue, the I-Menu in AOC monitors is really bad (nothing technical, just commercial bullshit, and I need a professional tool like this_

**its a false positive: ?**

https://www.virustotal.com/gui/file/a996f32846ebd71ad1c9fedeb934995fa237ca35c09671914b46dc252179d1ef/detection

**Bkav Pro**
W64.AIDetectMalware

**Cylance**
Unsafe

**Sangfor Engine Zero**
Trojan.Win32.Save.a

**SecureAge**
Malicious

**SentinelOne (Static ML)**
Static AI - Suspicious PE

**Skyhigh (SWG)**
BehavesLike.Win64.Dropper.wc

**Comment by scottaxcell** [comment]
I didn't click your link, but I'd say this is a false positive. You can look through the source code and dependencies yourself. Feel free to build the executable yourself with the following...
```
py -3 -m venv --upgrade-deps .venv
.venv\Scripts\activate.bat
pip install -r requirements.txt
pyinstaller cli.py --name winddcutil --onefile
```
