### ISSUE TITLE
winddcutil.exe capabilities 0: Failed to get capabilities string length

### ISSUE THREAD

**Issue by nobanzai** [scottaxcell/winddcutil#5]
I get

winddcutil.exe capabilities 0
Failed to get capabilities string length

for my DELL U4924DW monitor.
I don't use the precompiled executable, but compiled it myself.

Using ddcutil on Linux works as expected.

**Comment by scottaxcell** [comment]
I have ported `winddcutil` to Python, can you try the latest release to see if your issue has been resolved?

**Comment by nobanzai** [comment]
On Dienstag, 26. September 2023 16:28:25 CEST Scott Axcell wrote:
> I have ported ‘winddcutil’ to Python, can you try the latest release to see
> if your issue has been resolved?

At the moment I am on vacation.
I'll test it, when we are back.

Thx and bye.
Michael.

**Comment by nobanzai** [comment]
On Dienstag, 26. September 2023 16:31:23 CEST ***@***.*** 
wrote:
> On Dienstag, 26. September 2023 16:28:25 CEST Scott Axcell wrote:
> > I have ported ‘winddcutil’ to Python, can you try the latest release to
> > see
> > if your issue has been resolved?
> 
> At the moment I am on vacation.
> I'll test it, when we are back.
> 
> Thx and bye.
> Michael.

on second thought, I can't test it - and also can't use it at all, because on 
our machines no python is installed and we are not allowed to install it 8-(

Bad luck.

Bye.
Michael.

**Comment by scottaxcell** [comment]
You do not have to install Python. `winddcutil` is a standalone executable. Download the latest release from [here](https://github.com/scottaxcell/winddcutil/releases/tag/v2.0.0).

Then, run `winddcutil.exe capabilities 1`.

**Comment by nobanzai** [comment]
On Dienstag, 26. September 2023 23:45:48 CEST Scott Axcell wrote:
> You do not have to install Python. `winddcutil` is a standalone executable.
> Download the latest release from
> [here](https://github.com/scottaxcell/winddcutil/releases/tag/v2.0.0).
> 
> Then, run `winddcutil.exe capabilities 0`.

I am not allowed to bring binaries in any form into our company network.
So I'd need the source code to compile it myself. And for this to do, I guess 
I'd need python development packages?

Bye.
Michael.

**Comment by scottaxcell** [comment]
Feel free to download the 1.0.0 release and debug the C++ source code yourself. I do not own that particular monitor and so cannot reproduce the issue myself.
